[features]
seeds = false
skip-lint = false

[programs.localnet]
missing_account_validation = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
missing_authority_check = "HmbTLCmaGvZhKnn1Zfa1JVnp7vkMV4DYVxPLWBVoN65L"
incorrect_pda_derivation = "BPFLoaderUpgradeab1e11111111111111111111111"
unsafe_cpi_token_transfer = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
integer_overflow_state_bug = "11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 programs/**/tests/*.ts"

[workspace]
members = [
    "programs/01_missing_account_validation",
    "programs/02_missing_authority_check",
    "programs/03_incorrect_pda_derivation",
    "programs/04_unsafe_cpi_token_transfer",
    "programs/05_integer_overflow_state_bug"
]
